<?php 
header("Cache-Control: no-cache, must-revalidate"); // HTTP/1.1
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT"); // Date in the past
function server_time() 
{ 
   list($usec, $sec) = explode(" ", microtime()); 
   return ((float)$usec + (float)$sec); 
} 
$time_this_server = server_time();
$time_this_server_javascript = ($time_this_server * 1000);
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<script type="text/javascript" src="calc.js"></script>
<script type="text/javascript" src="custom_writer.js"></script>
<script type="text/javascript" src="custom_request.js"></script>
<link href="custom.css" rel="stylesheet" type="text/css" media="all">
</head>
<body>
<div id="select_container">
<select id="country1" onChange="var c1_c=this.options[this.selectedIndex].value; req1=new wrapper(c1_c,1)">
<option value = 'gmt'>Gmt </option>
<option value = 'afghanistan'>Afghanistan </option>
<option value = 'albania'>Albania </option>
<option value = 'algeria'>Algeria </option>
<option value = 'andorra'>Andorra </option>
<option value = 'angola'>Angola </option>
<option value = 'antigua_and_barbuda'>Antigua And Barbuda </option>
<option value = 'argentina'>Argentina </option>
<option value = 'argentina_san_luis'>Argentina San Luis </option>
<option value = 'armenia'>Armenia </option>
<option value = 'australia_australian_capital_territory'>Australia Australian Capital Territory </option>
<option value = 'australia_lord_howe_island'>Australia Lord Howe Island </option>
<option value = 'australia_new_south_wales'>Australia New South Wales </option>
<option value = 'australia_new_south_wales_broken_hill'>Australia New South Wales Broken Hill </option>
<option value = 'australia_northern_territory'>Australia Northern Territory </option>
<option value = 'australia_queensland'>Australia Queensland </option>
<option value = 'australia_south_australia'>Australia South Australia </option>
<option value = 'australia_tasmania'>Australia Tasmania </option>
<option value = 'australia_victoria'>Australia Victoria </option>
<option value = 'australia_western_australia'>Australia Western Australia </option>
<option value = 'australia_western_australia_border'>Australia Western Australia Border </option>
<option value = 'australia_ashmore_and_cartier_islands'>Australia Ashmore And Cartier Islands </option>
<option value = 'australia_christmas_island'>Australia Christmas Island </option>
<option value = 'australia_cocos_keeling_islands'>Australia Cocos Keeling Islands </option>
<option value = 'australia_norfolk_island'>Australia Norfolk Island </option>
<option value = 'austria'>Austria </option>
<option value = 'azerbaijan'>Azerbaijan </option>
<option value = 'bahamas'>Bahamas </option>
<option value = 'bahrain'>Bahrain </option>
<option value = 'bangladesh'>Bangladesh </option>
<option value = 'barbados'>Barbados </option>
<option value = 'belarus'>Belarus </option>
<option value = 'belgium'>Belgium </option>
<option value = 'belize'>Belize </option>
<option value = 'benin'>Benin </option>
<option value = 'bhutan'>Bhutan </option>
<option value = 'bolivarian_republic_of_venezuela'>Bolivarian Republic Of Venezuela </option>
<option value = 'bolivia'>Bolivia </option>
<option value = 'bosnia_and_herzegovina'>Bosnia And Herzegovina </option>
<option value = 'botswana'>Botswana </option>
<option value = 'brazil_acre'>Brazil Acre </option>
<option value = 'brazil_alagoas'>Brazil Alagoas </option>
<option value = 'brazil_amapa'>Brazil Amapa </option>
<option value = 'brazil_amazonas'>Brazil Amazonas </option>
<option value = 'brazil_amazonas_south_west'>Brazil Amazonas South West </option>
<option value = 'brazil_bahia'>Brazil Bahia </option>
<option value = 'brazil_ceara'>Brazil Ceara </option>
<option value = 'brazil_distrito_federal'>Brazil Distrito Federal </option>
<option value = 'brazil_espirto_santo'>Brazil Espirto Santo </option>
<option value = 'brazil_fernando_de_noronha'>Brazil Fernando De Noronha </option>
<option value = 'brazil_goias'>Brazil Goias </option>
<option value = 'brazil_maranhao'>Brazil Maranhao </option>
<option value = 'brazil_mato_grosso'>Brazil Mato Grosso </option>
<option value = 'brazil_mato_grosso_do_sul'>Brazil Mato Grosso Do Sul </option>
<option value = 'brazil_minas_gerais'>Brazil Minas Gerais </option>
<option value = 'brazil_para_east'>Brazil Para East </option>
<option value = 'brazil_para_west'>Brazil Para West </option>
<option value = 'brazil_paraiba'>Brazil Paraiba </option>
<option value = 'brazil_parana'>Brazil Parana </option>
<option value = 'brazil_pernambuco'>Brazil Pernambuco </option>
<option value = 'brazil_piaui'>Brazil Piaui </option>
<option value = 'brazil_rio_de_janeiro'>Brazil Rio De Janeiro </option>
<option value = 'brazil_rio_grande_do_norte'>Brazil Rio Grande Do Norte </option>
<option value = 'brazil_rio_grande_do_sul'>Brazil Rio Grande Do Sul </option>
<option value = 'brazil_rondonia'>Brazil Rondonia </option>
<option value = 'brazil_roraima'>Brazil Roraima </option>
<option value = 'brazil_santa_catarina'>Brazil Santa Catarina </option>
<option value = 'brazil_sao_paulo'>Brazil Sao Paulo </option>
<option value = 'brazil_sergipe'>Brazil Sergipe </option>
<option value = 'brazil_tocantins'>Brazil Tocantins </option>
<option value = 'brunei_darussalam'>Brunei Darussalam </option>
<option value = 'bulgaria'>Bulgaria </option>
<option value = 'burkina_faso'>Burkina Faso </option>
<option value = 'burundi'>Burundi </option>
<option value = 'cambodia'>Cambodia </option>
<option value = 'cameroon'>Cameroon </option>
<option value = 'canada_alberta'>Canada Alberta </option>
<option value = 'canada_british_columbia'>Canada British Columbia </option>
<option value = 'canada_dawson_creek'>Canada Dawson Creek </option>
<option value = 'canada_labrador'>Canada Labrador </option>
<option value = 'canada_labrador_port_hope_simpson'>Canada Labrador Port Hope Simpson </option>
<option value = 'canada_manitoba'>Canada Manitoba </option>
<option value = 'canada_new_brunswick'>Canada New Brunswick </option>
<option value = 'newfoundland_canada'>Newfoundland Canada </option>
<option value = 'canada_newfoundland'>Canada Newfoundland </option>
<option value = 'canada_northwest_territories'>Canada Northwest Territories </option>
<option value = 'canada_nova_scotia'>Canada Nova Scotia </option>
<option value = 'canada_nunavut_southampton_island'>Canada Nunavut Southampton Island </option>
<option value = 'canada_nunavut_coral_harbor'>Canada Nunavut Coral Harbor </option>
<option value = 'canada_nunavut_eastern'>Canada Nunavut Eastern </option>
<option value = 'canada_nunavut_central'>Canada Nunavut Central </option>
<option value = 'canada_nunavut_mountain'>Canada Nunavut Mountain </option>
<option value = 'canada_ontario_east'>Canada Ontario East </option>
<option value = 'canada_ontario_west'>Canada Ontario West </option>
<option value = 'canada_prince_edward_island'>Canada Prince Edward Island </option>
<option value = 'canada_quebec'>Canada Quebec </option>
<option value = 'canada_saskatchewan'>Canada Saskatchewan </option>
<option value = 'canada_saskatchewan_denare Beach'>Canada Saskatchewan Denare Beach </option>
<option value = 'canada_saskatchewan_creighton'>Canada Saskatchewan Creighton </option>
<option value = 'canada_saskatchewan_lloydminster'>Canada Saskatchewan Lloydminster </option>
<option value = 'canada_yukon'>Canada Yukon </option>
<option value = 'cape_verde'>Cape Verde </option>
<option value = 'central_african_republic'>Central African Republic </option>
<option value = 'chad'>Chad </option>
<option value = 'chile'>Chile </option>
<option value = 'chile_easter_island'>Chile Easter Island </option>
<option value = 'china'>China </option>
<option value = 'colombia'>Colombia </option>
<option value = 'comoros'>Comoros </option>
<option value = 'congo'>Congo </option>
<option value = 'costa_rica'>Costa Rica </option>
<option value = 'cote_divoire'>Cote Divoire </option>
<option value = 'croatia'>Croatia </option>
<option value = 'cuba'>Cuba </option>
<option value = 'cyprus'>Cyprus </option>
<option value = 'czech_republic'>Czech Republic </option>
<option value = 'democratic_peoples_republic_of_korea'>Democratic Peoples Republic Of Korea </option>
<option value = 'democratic_republic_of_the_congo_west'>Democratic Republic Of The Congo West </option>
<option value = 'democratic_republic_of_the_congo_east'>Democratic Republic Of The Congo East </option>
<option value = 'denmark'>Denmark </option>
<option value = 'denmark_faroe_islands'>Denmark Faroe Islands </option>
<option value = 'denmark_greenland'>Denmark Greenland </option>
<option value = 'denmark_greenland_ittoqqortoormiit'>Denmark Greenland Ittoqqortoormiit </option>
<option value = 'denmark_greenland_qaanaaq'>Denmark Greenland Qaanaaq </option>
<option value = 'denmark_greenland_danmarkshavn'>Denmark Greenland Danmarkshavn </option>
<option value = 'djibouti'>Djibouti </option>
<option value = 'dominica'>Dominica </option>
<option value = 'dominican_republic'>Dominican Republic </option>
<option value = 'ecuador'>Ecuador </option>
<option value = 'ecudaor_galapagos'>Ecudaor Galapagos </option>
<option value = 'egypt'>Egypt </option>
<option value = 'el_salvador'>El Salvador </option>
<option value = 'equatorial_guinea'>Equatorial Guinea </option>
<option value = 'eritrea'>Eritrea </option>
<option value = 'estonia'>Estonia </option>
<option value = 'ethiopia'>Ethiopia </option>
<option value = 'fiji'>Fiji </option>
<option value = 'finland'>Finland </option>
<option value = 'france'>France </option>
<option value = 'france_clipperton_island'>France Clipperton Island </option>
<option value = 'france_french_guiana'>France French Guiana </option>
<option value = 'france_french_polynesia'>France French Polynesia </option>
<option value = 'france_gambier_islands'>France Gambier Islands </option>
<option value = 'france_marquesas_islands'>France Marquesas Islands </option>
<option value = 'france_french_southern_and_antarctic_lands'>France French Southern And Antarctic Lands </option>
<option value = 'france_guadeloupe'>France Guadeloupe </option>
<option value = 'france_isles_esparses_bassas_da_india'>France Isles Esparses Bassas Da India </option>
<option value = 'france_isles_esparses_europa_island'>France Isles Esparses Europa Island </option>
<option value = 'france_isles_esparses_glorioso_islands'>France Isles Esparses Glorioso Islands </option>
<option value = 'france_isles_esparses_juan_de_nova_island'>France Isles Esparses Juan De Nova Island </option>
<option value = 'france_isles_esparses_tromelin_island'>France Isles Esparses Tromelin Island </option>
<option value = 'france_martinique'>France Martinique </option>
<option value = 'france_mayotte'>France Mayotte </option>
<option value = 'france_new_caledonia'>France New Caledonia </option>
<option value = 'france_reunion'>France Reunion </option>
<option value = 'france_saint_pierre_and_miquelon'>France Saint Pierre And Miquelon </option>
<option value = 'france_wallis_and_futuna'>France Wallis And Futuna </option>
<option value = 'gabon'>Gabon </option>
<option value = 'gambia'>Gambia </option>
<option value = 'georgia'>Georgia </option>
<option value = 'germany'>Germany </option>
<option value = 'ghana'>Ghana </option>
<option value = 'greece'>Greece </option>
<option value = 'grenada'>Grenada </option>
<option value = 'guatemala'>Guatemala </option>
<option value = 'guinea'>Guinea </option>
<option value = 'guinea_bissau'>Guinea Bissau </option>
<option value = 'guyana'>Guyana </option>
<option value = 'haiti'>Haiti </option>
<option value = 'honduras'>Honduras </option>
<option value = 'hungary'>Hungary </option>
<option value = 'iceland'>Iceland </option>
<option value = 'india'>India </option>
<option value = 'indonesia_western'>Indonesia Western </option>
<option value = 'indonesia_central'>Indonesia Central </option>
<option value = 'indonesia_eastern'>Indonesia Eastern </option>
<option value = 'iran'>Iran </option>
<option value = 'iraq'>Iraq </option>
<option value = 'ireland'>Ireland </option>
<option value = 'israel'>Israel </option>
<option value = 'italy'>Italy </option>
<option value = 'jamaica'>Jamaica </option>
<option value = 'japan'>Japan </option>
<option value = 'jordan'>Jordan </option>
<option value = 'kazakhstan_west'>Kazakhstan West </option>
<option value = 'kazakhstan_east'>Kazakhstan East </option>
<option value = 'kenya'>Kenya </option>
<option value = 'kiribati_gilbert_islands'>Kiribati Gilbert Islands </option>
<option value = 'kiribati_phoenix_islands'>Kiribati Phoenix Islands </option>
<option value = 'kiribati_line_islands'>Kiribati Line Islands </option>
<option value = 'kuwait'>Kuwait </option>
<option value = 'kyrgyzstan'>Kyrgyzstan </option>
<option value = 'lao_peoples_democratic_republic'>Lao Peoples Democratic Republic </option>
<option value = 'latvia'>Latvia </option>
<option value = 'lebanon'>Lebanon </option>
<option value = 'lesotho'>Lesotho </option>
<option value = 'liberia'>Liberia </option>
<option value = 'libyan_arab_jamahiriya'>Libyan Arab Jamahiriya </option>
<option value = 'liechtenstein'>Liechtenstein </option>
<option value = 'lithuania'>Lithuania </option>
<option value = 'luxembourg'>Luxembourg </option>
<option value = 'madagascar'>Madagascar </option>
<option value = 'malawi'>Malawi </option>
<option value = 'malaysia'>Malaysia </option>
<option value = 'maldives'>Maldives </option>
<option value = 'mali'>Mali </option>
<option value = 'malta'>Malta </option>
<option value = 'marshall_islands'>Marshall Islands </option>
<option value = 'mauritania'>Mauritania </option>
<option value = 'mauritius'>Mauritius </option>
<option value = 'mexico_aguascalientes'>Mexico Aguascalientes </option>
<option value = 'mexico_baja_california'>Mexico Baja California </option>
<option value = 'mexico_baja_california_sur'>Mexico Baja California Sur </option>
<option value = 'mexico_campeche'>Mexico Campeche </option>
<option value = 'mexico_chiapas'>Mexico Chiapas </option>
<option value = 'mexico_chihuahua'>Mexico Chihuahua </option>
<option value = 'mexico_coahuila'>Mexico Coahuila </option>
<option value = 'mexico_colima'>Mexico Colima </option>
<option value = 'mexico_durango'>Mexico Durango </option>
<option value = 'mexico_guanajuato'>Mexico Guanajuato </option>
<option value = 'mexico_guerrero'>Mexico Guerrero </option>
<option value = 'mexico_hidalgo'>Mexico Hidalgo </option>
<option value = 'mexico_jalisco'>Mexico Jalisco </option>
<option value = 'mexico_mexican_federal_district'>Mexico Mexican Federal District </option>
<option value = 'mexico_michoacan'>Mexico Michoacan </option>
<option value = 'mexico_morelos'>Mexico Morelos </option>
<option value = 'mexico_nayarit'>Mexico Nayarit </option>
<option value = 'mexico_nuevo_leon'>Mexico Nuevo Leon </option>
<option value = 'mexico_oaxaca'>Mexico Oaxaca </option>
<option value = 'mexico_puebla'>Mexico Puebla </option>
<option value = 'mexico_queretaro'>Mexico Queretaro </option>
<option value = 'mexico_quintana_roo'>Mexico Quintana Roo </option>
<option value = 'mexico_san_luis_potosi'>Mexico San Luis Potosi </option>
<option value = 'mexico_sinaloa'>Mexico Sinaloa </option>
<option value = 'mexico_sonora'>Mexico Sonora </option>
<option value = 'mexico_state_of_mexico'>Mexico State Of Mexico </option>
<option value = 'mexico_tabasco'>Mexico Tabasco </option>
<option value = 'mexico_tamaulipas'>Mexico Tamaulipas </option>
<option value = 'mexico_tlaxcala'>Mexico Tlaxcala </option>
<option value = 'mexico_veracruz'>Mexico Veracruz </option>
<option value = 'mexico_yucatan'>Mexico Yucatan </option>
<option value = 'mexico_zacatecas'>Mexico Zacatecas </option>
<option value = 'micronesia'>Micronesia </option>
<option value = 'monaco'>Monaco </option>
<option value = 'mongolia_west'>Mongolia West </option>
<option value = 'mongolia_east'>Mongolia East </option>
<option value = 'montenegro'>Montenegro </option>
<option value = 'morocco'>Morocco </option>
<option value = 'mozambique'>Mozambique </option>
<option value = 'myanmar'>Myanmar </option>
<option value = 'namibia'>Namibia </option>
<option value = 'nauru'>Nauru </option>
<option value = 'nepal'>Nepal </option>
<option value = 'netherlands'>Netherlands </option>
<option value = 'netherlands_antilles'>Netherlands Antilles </option>
<option value = 'netherlands_aruba'>Netherlands Aruba </option>
<option value = 'new_zealand'>New Zealand </option>
<option value = 'new_zealand_chatham_islands'>New Zealand Chatham Islands </option>
<option value = 'new_zealand_cook_islands'>New Zealand Cook Islands </option>
<option value = 'new_zealand_niue'>New Zealand Niue </option>
<option value = 'new_zealand_tokelau'>New Zealand Tokelau </option>
<option value = 'nicaragua'>Nicaragua </option>
<option value = 'niger'>Niger </option>
<option value = 'nigeria'>Nigeria </option>
<option value = 'norway'>Norway </option>
<option value = 'norway_bouvet_island'>Norway Bouvet Island </option>
<option value = 'norway_jan_mayen'>Norway Jan Mayen </option>
<option value = 'norway_svalbard'>Norway Svalbard </option>
<option value = 'oman'>Oman </option>
<option value = 'pakistan'>Pakistan </option>
<option value = 'palau'>Palau </option>
<option value = 'panama'>Panama </option>
<option value = 'papua_new_guinea'>Papua New Guinea </option>
<option value = 'paraguay'>Paraguay </option>
<option value = 'peru'>Peru </option>
<option value = 'philippines'>Philippines </option>
<option value = 'poland'>Poland </option>
<option value = 'portugal'>Portugal </option>
<option value = 'portugal_azores'>Portugal Azores </option>
<option value = 'qatar'>Qatar </option>
<option value = 'republic_of_korea'>Republic Of Korea </option>
<option value = 'republic_of_moldova'>Republic Of Moldova </option>
<option value = 'romania'>Romania </option>
<option value = 'russia_adygea'>Russia Adygea </option>
<option value = 'russia_agin_buryat'>Russia Agin Buryat </option>
<option value = 'russia_altaskiy_kray'>Russia Altaskiy Kray </option>
<option value = 'russia_altai_republic'>Russia Altai Republic </option>
<option value = 'russia_amur'>Russia Amur </option>
<option value = 'russia_arkhangel'>Russia Arkhangel </option>
<option value = 'russia_astrakhan'>Russia Astrakhan </option>
<option value = 'russia_bashkortostan'>Russia Bashkortostan </option>
<option value = 'russia_belgorod'>Russia Belgorod </option>
<option value = 'russia_bryansk'>Russia Bryansk </option>
<option value = 'russia_buryatia'>Russia Buryatia </option>
<option value = 'russia_chechnya'>Russia Chechnya </option>
<option value = 'russia_chelyabinsk'>Russia Chelyabinsk </option>
<option value = 'russia_chita'>Russia Chita </option>
<option value = 'russia_chukot'>Russia Chukot </option>
<option value = 'russia_chuvashia'>Russia Chuvashia </option>
<option value = 'russia_dagestan'>Russia Dagestan </option>
<option value = 'russia_evenki'>Russia Evenki </option>
<option value = 'russia_ingushetia'>Russia Ingushetia </option>
<option value = 'russia_irkutsk'>Russia Irkutsk </option>
<option value = 'russia_ivanovo'>Russia Ivanovo </option>
<option value = 'russia_jewish_autonomous_oblast'>Russia Jewish Autonomous Oblast </option>
<option value = 'russia_kabardino_balkaria'>Russia Kabardino Balkaria </option>
<option value = 'russia_kaliningrad'>Russia Kaliningrad </option>
<option value = 'russia_kalmykia'>Russia Kalmykia </option>
<option value = 'russia_kaluga'>Russia Kaluga </option>
<option value = 'russia_kamchatka'>Russia Kamchatka </option>
<option value = 'russia_karachay_cherkessia'>Russia Karachay Cherkessia </option>
<option value = 'russia_karelia'>Russia Karelia </option>
<option value = 'russia_kemerovo'>Russia Kemerovo </option>
<option value = 'russia_khabarovsk'>Russia Khabarovsk </option>
<option value = 'russia_khakassia'>Russia Khakassia </option>
<option value = 'russia_khanty_mansi'>Russia Khanty Mansi </option>
<option value = 'russia_kirov'>Russia Kirov </option>
<option value = 'russia_komi'>Russia Komi </option>
<option value = 'russia_koryak'>Russia Koryak </option>
<option value = 'russia_kostroma'>Russia Kostroma </option>
<option value = 'russia_krasnodar'>Russia Krasnodar </option>
<option value = 'russia_krasnoyarsk'>Russia Krasnoyarsk </option>
<option value = 'russia_kurgan'>Russia Kurgan </option>
<option value = 'russia_kursk'>Russia Kursk </option>
<option value = 'russia_leningradskaya_oblast'>Russia Leningradskaya Oblast </option>
<option value = 'russia_lipetsk'>Russia Lipetsk </option>
<option value = 'russia_magadan'>Russia Magadan </option>
<option value = 'russia_mari_el'>Russia Mari El </option>
<option value = 'russia_mordovia'>Russia Mordovia </option>
<option value = 'russia_moscow_city'>Russia Moscow City </option>
<option value = 'russia_moskva'>Russia Moskva </option>
<option value = 'russia_murmansk'>Russia Murmansk </option>
<option value = 'russia_nenets'>Russia Nenets </option>
<option value = 'russia_nizhniy_novgorod'>Russia Nizhniy Novgorod </option>
<option value = 'russia_north_ossetia_alania'>Russia North Ossetia Alania </option>
<option value = 'russia_novgorod'>Russia Novgorod </option>
<option value = 'russia_novosibirsk'>Russia Novosibirsk </option>
<option value = 'russia_omsk'>Russia Omsk </option>
<option value = 'russia_orenburg'>Russia Orenburg </option>
<option value = 'russia_oryol'>Russia Oryol </option>
<option value = 'russia_penza'>Russia Penza </option>
<option value = 'russia_perm_krai'>Russia Perm Krai </option>
<option value = 'russia_primorskiy'>Russia Primorskiy </option>
<option value = 'russia_pskov'>Russia Pskov </option>
<option value = 'russia_rostov'>Russia Rostov </option>
<option value = 'russia_ryazan'>Russia Ryazan </option>
<option value = 'russia_sakha_west'>Russia Sakha West </option>
<option value = 'russia_sakha_central'>Russia Sakha Central </option>
<option value = 'russia_sakha_east'>Russia Sakha East </option>
<option value = 'russia_sakhalin'>Russia Sakhalin </option>
<option value = 'russia_sakhalin_kuril_islands'>Russia Sakhalin Kuril Islands </option>
<option value = 'russia_samara'>Russia Samara </option>
<option value = 'russia_saratov'>Russia Saratov </option>
<option value = 'russia_smolensk'>Russia Smolensk </option>
<option value = 'russia_st_petersburg_city'>Russia St Petersburg City </option>
<option value = 'russia_stavropol'>Russia Stavropol </option>
<option value = 'russia_sverdlovsk'>Russia Sverdlovsk </option>
<option value = 'russia_tambov'>Russia Tambov </option>
<option value = 'russia_tatarstan'>Russia Tatarstan </option>
<option value = 'russia_taymyr'>Russia Taymyr </option>
<option value = 'russia_tomsk'>Russia Tomsk </option>
<option value = 'russia_tula'>Russia Tula </option>
<option value = 'russia_tuva'>Russia Tuva </option>
<option value = 'russia_tver'>Russia Tver </option>
<option value = 'russia_tyumen'>Russia Tyumen </option>
<option value = 'russia_udmurtia'>Russia Udmurtia </option>
<option value = 'russia_ulyanovsk'>Russia Ulyanovsk </option>
<option value = 'russia_ust_ordyn_buryat'>Russia Ust Ordyn Buryat </option>
<option value = 'russia_vladimir'>Russia Vladimir </option>
<option value = 'russia_volgograd'>Russia Volgograd </option>
<option value = 'russia_vologda'>Russia Vologda </option>
<option value = 'russia_voronezh'>Russia Voronezh </option>
<option value = 'russia_yamalo_nenets'>Russia Yamalo Nenets </option>
<option value = 'russia_yaroslavl'>Russia Yaroslavl </option>
<option value = 'rwanda'>Rwanda </option>
<option value = 'saint_kitts_and_nevis'>Saint Kitts And Nevis </option>
<option value = 'saint_lucia'>Saint Lucia </option>
<option value = 'saint_vincent_and_the_grenadines'>Saint Vincent And The Grenadines </option>
<option value = 'samoa'>Samoa </option>
<option value = 'san_marino'>San Marino </option>
<option value = 'sao_tome_and_principe'>Sao Tome And Principe </option>
<option value = 'saudi_arabia'>Saudi Arabia </option>
<option value = 'senegal'>Senegal </option>
<option value = 'serbia'>Serbia </option>
<option value = 'seychelles'>Seychelles </option>
<option value = 'sierra_leone'>Sierra Leone </option>
<option value = 'singapore'>Singapore </option>
<option value = 'slovakia'>Slovakia </option>
<option value = 'slovenia'>Slovenia </option>
<option value = 'solomon_islands'>Solomon Islands </option>
<option value = 'somalia'>Somalia </option>
<option value = 'south_africa'>South Africa </option>
<option value = 'spain'>Spain </option>
<option value = 'spain_canary_islands'>Spain Canary Islands </option>
<option value = 'sri_lanka'>Sri Lanka </option>
<option value = 'sudan'>Sudan </option>
<option value = 'suriname'>Suriname </option>
<option value = 'swaziland'>Swaziland </option>
<option value = 'sweden'>Sweden </option>
<option value = 'switzerland'>Switzerland </option>
<option value = 'syria'>Syria </option>
<option value = 'syrian_arab_republic'>Syrian Arab Republic </option>
<option value = 'tajikistan'>Tajikistan </option>
<option value = 'thailand'>Thailand </option>
<option value = 'fyro_macedonia'>Fyro Macedonia </option>
<option value = 'timor_leste'>Timor Leste </option>
<option value = 'togo'>Togo </option>
<option value = 'tonga'>Tonga </option>
<option value = 'trinidad_and_tobago'>Trinidad And Tobago </option>
<option value = 'tunisia'>Tunisia </option>
<option value = 'turkey'>Turkey </option>
<option value = 'turkmenistan'>Turkmenistan </option>
<option value = 'tuvalu'>Tuvalu </option>
<option value = 'uganda'>Uganda </option>
<option value = 'ukraine'>Ukraine </option>
<option value = 'united_arab_emirates'>United Arab Emirates </option>
<option value = 'uk'>Uk </option>
<option value = 'uk_akrotiri'>Uk Akrotiri </option>
<option value = 'uk_anguilla'>Uk Anguilla </option>
<option value = 'uk_bermuda'>Uk Bermuda </option>
<option value = 'uk_british_indian_ocean_territory'>Uk British Indian Ocean Territory </option>
<option value = 'uk_british_virgin_islands'>Uk British Virgin Islands </option>
<option value = 'uk_cayman_islands'>Uk Cayman Islands </option>
<option value = 'uk_dhekelia'>Uk Dhekelia </option>
<option value = 'uk_falkland_islands'>Uk Falkland Islands </option>
<option value = 'uk_gibraltar'>Uk Gibraltar </option>
<option value = 'uk_guernsey'>Uk Guernsey </option>
<option value = 'uk_isle_of_man'>Uk Isle Of Man </option>
<option value = 'uk_jersey'>Uk Jersey </option>
<option value = 'uk_montserrat'>Uk Montserrat </option>
<option value = 'uk_pitcairn_islands'>Uk Pitcairn Islands </option>
<option value = 'uk_saint_helena_ascensiont_tristan_da_cuhna'>Uk Saint Helena Ascensiont Tristan Da Cuhna </option>
<option value = 'uk_south_georgia_and_the_south_sandwich_islands'>Uk South Georgia And The South Sandwich Islands </option>
<option value = 'uk_turks_and_caicos_islands'>Uk Turks And Caicos Islands </option>
<option value = 'united_republic_of_tanzania'>United Republic Of Tanzania </option>
<option value = 'usa_alabama'>Usa Alabama </option>
<option value = 'usa_alabama_phenix_city_unofficial'>Usa Alabama Phenix City Unofficial </option>
<option value = 'usa_alaska'>Usa Alaska </option>
<option value = 'usa_aleutian_islands'>Usa Aleutian Islands </option>
<option value = 'usa_arizona'>Usa Arizona </option>
<option value = 'usa_arizona_navajo_nation'>Usa Arizona Navajo Nation </option>
<option value = 'usa_arizona_navajo_nation_hopi_reservation'>Usa Arizona Navajo Nation Hopi Reservation </option>
<option value = 'usa_arkansas'>Usa Arkansas </option>
<option value = 'usa_california'>Usa California </option>
<option value = 'usa_colorado'>Usa Colorado </option>
<option value = 'usa_connecticut'>Usa Connecticut </option>
<option value = 'usa_delaware'>Usa Delaware </option>
<option value = 'usa_district_of_columbia'>Usa District Of Columbia </option>
<option value = 'usa_florida'>Usa Florida </option>
<option value = 'usa_florida_west'>Usa Florida West </option>
<option value = 'usa_georgia'>Usa Georgia </option>
<option value = 'usa_hawaii'>Usa Hawaii </option>
<option value = 'usa_idaho_south'>Usa Idaho South </option>
<option value = 'usa_idaho_north'>Usa Idaho North </option>
<option value = 'usa_illinois'>Usa Illinois </option>
<option value = 'usa_indiana'>Usa Indiana </option>
<option value = 'usa_indiana_counties'>Usa Indiana Counties </option>
<option value = 'usa_iowa'>Usa Iowa </option>
<option value = 'usa_kansas'>Usa Kansas </option>
<option value = 'usa_kansas_counties'>Usa Kansas Counties </option>
<option value = 'usa_kentucky_west'>Usa Kentucky West </option>
<option value = 'usa_kentucky_east'>Usa Kentucky East </option>
<option value = 'usa_louisiana'>Usa Louisiana </option>
<option value = 'usa_maine'>Usa Maine </option>
<option value = 'usa_maryland'>Usa Maryland </option>
<option value = 'usa_massachusetts'>Usa Massachusetts </option>
<option value = 'usa_michigan'>Usa Michigan </option>
<option value = 'usa_michigan_counties'>Usa Michigan Counties </option>
<option value = 'usa_minnesota'>Usa Minnesota </option>
<option value = 'usa_mississippi'>Usa Mississippi </option>
<option value = 'usa_missouri'>Usa Missouri </option>
<option value = 'usa_montana'>Usa Montana </option>
<option value = 'usa_nebraska_west'>Usa Nebraska West </option>
<option value = 'usa_nebraska_east_central'>Usa Nebraska East Central </option>
<option value = 'usa_nevada'>Usa Nevada </option>
<option value = 'usa_nevada_others'>Usa Nevada Others </option>
<option value = 'usa_new_hampshire'>Usa New Hampshire </option>
<option value = 'usa_new_jersey'>Usa New Jersey </option>
<option value = 'usa_new_mexico'>Usa New Mexico </option>
<option value = 'usa_new_york'>Usa New York </option>
<option value = 'usa_north_carolina'>Usa North Carolina </option>
<option value = 'usa_north_dakota'>Usa North Dakota </option>
<option value = 'usa_north_dakota_south_west'>Usa North Dakota South West </option>
<option value = 'usa_ohio'>Usa Ohio </option>
<option value = 'usa_oklahoma'>Usa Oklahoma </option>
<option value = 'usa_oklahoma_kenton'>Usa Oklahoma Kenton </option>
<option value = 'usa_oregon'>Usa Oregon </option>
<option value = 'usa_oregon_northern_malheur_county'>Usa Oregon Northern Malheur County </option>
<option value = 'usa_pennsylvania'>Usa Pennsylvania </option>
<option value = 'usa_rhode_island'>Usa Rhode Island </option>
<option value = 'usa_south_carolina'>Usa South Carolina </option>
<option value = 'usa_south_dakota_west'>Usa South Dakota West </option>
<option value = 'usa_south_dakota_east'>Usa South Dakota East </option>
<option value = 'usa_tennessee'>Usa Tennessee </option>
<option value = 'usa_tennessee_east'>Usa Tennessee East </option>
<option value = 'usa_texas'>Usa Texas </option>
<option value = 'usa_texas_counties'>Usa Texas Counties </option>
<option value = 'usa_utah'>Usa Utah </option>
<option value = 'usa_vermont'>Usa Vermont </option>
<option value = 'usa_virginia'>Usa Virginia </option>
<option value = 'usa_washington'>Usa Washington </option>
<option value = 'usa_west_virginia'>Usa West Virginia </option>
<option value = 'usa_wisconsin'>Usa Wisconsin </option>
<option value = 'usa_wyoming'>Usa Wyoming </option>
<option value = 'usa_american_samoa'>Usa American Samoa </option>
<option value = 'usa_american_guam'>Usa American Guam </option>
<option value = 'usa_navassa_island'>Usa Navassa Island </option>
<option value = 'usa_northern_mariana_islands'>Usa Northern Mariana Islands </option>
<option value = 'usa_puerto_rico'>Usa Puerto Rico </option>
<option value = 'usa_pir_baker_island'>Usa Pir Baker Island </option>
<option value = 'usa_pir_howland_island'>Usa Pir Howland Island </option>
<option value = 'usa_pir_jarvis_island'>Usa Pir Jarvis Island </option>
<option value = 'usa_pir_johnston_atoll'>Usa Pir Johnston Atoll </option>
<option value = 'usa_pir_kingman_reef'>Usa Pir Kingman Reef </option>
<option value = 'usa_pir_midway_islands'>Usa Pir Midway Islands </option>
<option value = 'usa_pir_palmyra_atoll'>Usa Pir Palmyra Atoll </option>
<option value = 'usa_virgin_islands'>Usa Virgin Islands </option>
<option value = 'usa_wake_island'>Usa Wake Island </option>
<option value = 'uruguay'>Uruguay </option>
<option value = 'uzbekistan'>Uzbekistan </option>
<option value = 'vanuatu'>Vanuatu </option>
<option value = 'viet_nam'>Viet Nam </option>
<option value = 'western_sahara'>Western Sahara </option>
<option value = 'yemen'>Yemen </option>
<option value = 'zambia'>Zambia </option>
<option value = 'zimbabwe'>Zimbabwe </option>
</select>
<select id="country2" onChange="var c2_c=this.options[this.selectedIndex].value; req1=new wrapper(c2_c,2)">
<option value = 'gmt'>Gmt </option>
<option value = 'afghanistan'>Afghanistan </option>
<option value = 'albania'>Albania </option>
<option value = 'algeria'>Algeria </option>
<option value = 'andorra'>Andorra </option>
<option value = 'angola'>Angola </option>
<option value = 'antigua_and_barbuda'>Antigua And Barbuda </option>
<option value = 'argentina'>Argentina </option>
<option value = 'argentina_san_luis'>Argentina San Luis </option>
<option value = 'armenia'>Armenia </option>
<option value = 'australia_australian_capital_territory'>Australia Australian Capital Territory </option>
<option value = 'australia_lord_howe_island'>Australia Lord Howe Island </option>
<option value = 'australia_new_south_wales'>Australia New South Wales </option>
<option value = 'australia_new_south_wales_broken_hill'>Australia New South Wales Broken Hill </option>
<option value = 'australia_northern_territory'>Australia Northern Territory </option>
<option value = 'australia_queensland'>Australia Queensland </option>
<option value = 'australia_south_australia'>Australia South Australia </option>
<option value = 'australia_tasmania'>Australia Tasmania </option>
<option value = 'australia_victoria'>Australia Victoria </option>
<option value = 'australia_western_australia'>Australia Western Australia </option>
<option value = 'australia_western_australia_border'>Australia Western Australia Border </option>
<option value = 'australia_ashmore_and_cartier_islands'>Australia Ashmore And Cartier Islands </option>
<option value = 'australia_christmas_island'>Australia Christmas Island </option>
<option value = 'australia_cocos_keeling_islands'>Australia Cocos Keeling Islands </option>
<option value = 'australia_norfolk_island'>Australia Norfolk Island </option>
<option value = 'austria'>Austria </option>
<option value = 'azerbaijan'>Azerbaijan </option>
<option value = 'bahamas'>Bahamas </option>
<option value = 'bahrain'>Bahrain </option>
<option value = 'bangladesh'>Bangladesh </option>
<option value = 'barbados'>Barbados </option>
<option value = 'belarus'>Belarus </option>
<option value = 'belgium'>Belgium </option>
<option value = 'belize'>Belize </option>
<option value = 'benin'>Benin </option>
<option value = 'bhutan'>Bhutan </option>
<option value = 'bolivarian_republic_of_venezuela'>Bolivarian Republic Of Venezuela </option>
<option value = 'bolivia'>Bolivia </option>
<option value = 'bosnia_and_herzegovina'>Bosnia And Herzegovina </option>
<option value = 'botswana'>Botswana </option>
<option value = 'brazil_acre'>Brazil Acre </option>
<option value = 'brazil_alagoas'>Brazil Alagoas </option>
<option value = 'brazil_amapa'>Brazil Amapa </option>
<option value = 'brazil_amazonas'>Brazil Amazonas </option>
<option value = 'brazil_amazonas_south_west'>Brazil Amazonas South West </option>
<option value = 'brazil_bahia'>Brazil Bahia </option>
<option value = 'brazil_ceara'>Brazil Ceara </option>
<option value = 'brazil_distrito_federal'>Brazil Distrito Federal </option>
<option value = 'brazil_espirto_santo'>Brazil Espirto Santo </option>
<option value = 'brazil_fernando_de_noronha'>Brazil Fernando De Noronha </option>
<option value = 'brazil_goias'>Brazil Goias </option>
<option value = 'brazil_maranhao'>Brazil Maranhao </option>
<option value = 'brazil_mato_grosso'>Brazil Mato Grosso </option>
<option value = 'brazil_mato_grosso_do_sul'>Brazil Mato Grosso Do Sul </option>
<option value = 'brazil_minas_gerais'>Brazil Minas Gerais </option>
<option value = 'brazil_para_east'>Brazil Para East </option>
<option value = 'brazil_para_west'>Brazil Para West </option>
<option value = 'brazil_paraiba'>Brazil Paraiba </option>
<option value = 'brazil_parana'>Brazil Parana </option>
<option value = 'brazil_pernambuco'>Brazil Pernambuco </option>
<option value = 'brazil_piaui'>Brazil Piaui </option>
<option value = 'brazil_rio_de_janeiro'>Brazil Rio De Janeiro </option>
<option value = 'brazil_rio_grande_do_norte'>Brazil Rio Grande Do Norte </option>
<option value = 'brazil_rio_grande_do_sul'>Brazil Rio Grande Do Sul </option>
<option value = 'brazil_rondonia'>Brazil Rondonia </option>
<option value = 'brazil_roraima'>Brazil Roraima </option>
<option value = 'brazil_santa_catarina'>Brazil Santa Catarina </option>
<option value = 'brazil_sao_paulo'>Brazil Sao Paulo </option>
<option value = 'brazil_sergipe'>Brazil Sergipe </option>
<option value = 'brazil_tocantins'>Brazil Tocantins </option>
<option value = 'brunei_darussalam'>Brunei Darussalam </option>
<option value = 'bulgaria'>Bulgaria </option>
<option value = 'burkina_faso'>Burkina Faso </option>
<option value = 'burundi'>Burundi </option>
<option value = 'cambodia'>Cambodia </option>
<option value = 'cameroon'>Cameroon </option>
<option value = 'canada_alberta'>Canada Alberta </option>
<option value = 'canada_british_columbia'>Canada British Columbia </option>
<option value = 'canada_dawson_creek'>Canada Dawson Creek </option>
<option value = 'canada_labrador'>Canada Labrador </option>
<option value = 'canada_labrador_port_hope_simpson'>Canada Labrador Port Hope Simpson </option>
<option value = 'canada_manitoba'>Canada Manitoba </option>
<option value = 'canada_new_brunswick'>Canada New Brunswick </option>
<option value = 'newfoundland_canada'>Newfoundland Canada </option>
<option value = 'canada_newfoundland'>Canada Newfoundland </option>
<option value = 'canada_northwest_territories'>Canada Northwest Territories </option>
<option value = 'canada_nova_scotia'>Canada Nova Scotia </option>
<option value = 'canada_nunavut_southampton_island'>Canada Nunavut Southampton Island </option>
<option value = 'canada_nunavut_coral_harbor'>Canada Nunavut Coral Harbor </option>
<option value = 'canada_nunavut_eastern'>Canada Nunavut Eastern </option>
<option value = 'canada_nunavut_central'>Canada Nunavut Central </option>
<option value = 'canada_nunavut_mountain'>Canada Nunavut Mountain </option>
<option value = 'canada_ontario_east'>Canada Ontario East </option>
<option value = 'canada_ontario_west'>Canada Ontario West </option>
<option value = 'canada_prince_edward_island'>Canada Prince Edward Island </option>
<option value = 'canada_quebec'>Canada Quebec </option>
<option value = 'canada_saskatchewan'>Canada Saskatchewan </option>
<option value = 'canada_saskatchewan_denare Beach'>Canada Saskatchewan Denare Beach </option>
<option value = 'canada_saskatchewan_creighton'>Canada Saskatchewan Creighton </option>
<option value = 'canada_saskatchewan_lloydminster'>Canada Saskatchewan Lloydminster </option>
<option value = 'canada_yukon'>Canada Yukon </option>
<option value = 'cape_verde'>Cape Verde </option>
<option value = 'central_african_republic'>Central African Republic </option>
<option value = 'chad'>Chad </option>
<option value = 'chile'>Chile </option>
<option value = 'chile_easter_island'>Chile Easter Island </option>
<option value = 'china'>China </option>
<option value = 'colombia'>Colombia </option>
<option value = 'comoros'>Comoros </option>
<option value = 'congo'>Congo </option>
<option value = 'costa_rica'>Costa Rica </option>
<option value = 'cote_divoire'>Cote Divoire </option>
<option value = 'croatia'>Croatia </option>
<option value = 'cuba'>Cuba </option>
<option value = 'cyprus'>Cyprus </option>
<option value = 'czech_republic'>Czech Republic </option>
<option value = 'democratic_peoples_republic_of_korea'>Democratic Peoples Republic Of Korea </option>
<option value = 'democratic_republic_of_the_congo_west'>Democratic Republic Of The Congo West </option>
<option value = 'democratic_republic_of_the_congo_east'>Democratic Republic Of The Congo East </option>
<option value = 'denmark'>Denmark </option>
<option value = 'denmark_faroe_islands'>Denmark Faroe Islands </option>
<option value = 'denmark_greenland'>Denmark Greenland </option>
<option value = 'denmark_greenland_ittoqqortoormiit'>Denmark Greenland Ittoqqortoormiit </option>
<option value = 'denmark_greenland_qaanaaq'>Denmark Greenland Qaanaaq </option>
<option value = 'denmark_greenland_danmarkshavn'>Denmark Greenland Danmarkshavn </option>
<option value = 'djibouti'>Djibouti </option>
<option value = 'dominica'>Dominica </option>
<option value = 'dominican_republic'>Dominican Republic </option>
<option value = 'ecuador'>Ecuador </option>
<option value = 'ecudaor_galapagos'>Ecudaor Galapagos </option>
<option value = 'egypt'>Egypt </option>
<option value = 'el_salvador'>El Salvador </option>
<option value = 'equatorial_guinea'>Equatorial Guinea </option>
<option value = 'eritrea'>Eritrea </option>
<option value = 'estonia'>Estonia </option>
<option value = 'ethiopia'>Ethiopia </option>
<option value = 'fiji'>Fiji </option>
<option value = 'finland'>Finland </option>
<option value = 'france'>France </option>
<option value = 'france_clipperton_island'>France Clipperton Island </option>
<option value = 'france_french_guiana'>France French Guiana </option>
<option value = 'france_french_polynesia'>France French Polynesia </option>
<option value = 'france_gambier_islands'>France Gambier Islands </option>
<option value = 'france_marquesas_islands'>France Marquesas Islands </option>
<option value = 'france_french_southern_and_antarctic_lands'>France French Southern And Antarctic Lands </option>
<option value = 'france_guadeloupe'>France Guadeloupe </option>
<option value = 'france_isles_esparses_bassas_da_india'>France Isles Esparses Bassas Da India </option>
<option value = 'france_isles_esparses_europa_island'>France Isles Esparses Europa Island </option>
<option value = 'france_isles_esparses_glorioso_islands'>France Isles Esparses Glorioso Islands </option>
<option value = 'france_isles_esparses_juan_de_nova_island'>France Isles Esparses Juan De Nova Island </option>
<option value = 'france_isles_esparses_tromelin_island'>France Isles Esparses Tromelin Island </option>
<option value = 'france_martinique'>France Martinique </option>
<option value = 'france_mayotte'>France Mayotte </option>
<option value = 'france_new_caledonia'>France New Caledonia </option>
<option value = 'france_reunion'>France Reunion </option>
<option value = 'france_saint_pierre_and_miquelon'>France Saint Pierre And Miquelon </option>
<option value = 'france_wallis_and_futuna'>France Wallis And Futuna </option>
<option value = 'gabon'>Gabon </option>
<option value = 'gambia'>Gambia </option>
<option value = 'georgia'>Georgia </option>
<option value = 'germany'>Germany </option>
<option value = 'ghana'>Ghana </option>
<option value = 'greece'>Greece </option>
<option value = 'grenada'>Grenada </option>
<option value = 'guatemala'>Guatemala </option>
<option value = 'guinea'>Guinea </option>
<option value = 'guinea_bissau'>Guinea Bissau </option>
<option value = 'guyana'>Guyana </option>
<option value = 'haiti'>Haiti </option>
<option value = 'honduras'>Honduras </option>
<option value = 'hungary'>Hungary </option>
<option value = 'iceland'>Iceland </option>
<option value = 'india'>India </option>
<option value = 'indonesia_western'>Indonesia Western </option>
<option value = 'indonesia_central'>Indonesia Central </option>
<option value = 'indonesia_eastern'>Indonesia Eastern </option>
<option value = 'iran'>Iran </option>
<option value = 'iraq'>Iraq </option>
<option value = 'ireland'>Ireland </option>
<option value = 'israel'>Israel </option>
<option value = 'italy'>Italy </option>
<option value = 'jamaica'>Jamaica </option>
<option value = 'japan'>Japan </option>
<option value = 'jordan'>Jordan </option>
<option value = 'kazakhstan_west'>Kazakhstan West </option>
<option value = 'kazakhstan_east'>Kazakhstan East </option>
<option value = 'kenya'>Kenya </option>
<option value = 'kiribati_gilbert_islands'>Kiribati Gilbert Islands </option>
<option value = 'kiribati_phoenix_islands'>Kiribati Phoenix Islands </option>
<option value = 'kiribati_line_islands'>Kiribati Line Islands </option>
<option value = 'kuwait'>Kuwait </option>
<option value = 'kyrgyzstan'>Kyrgyzstan </option>
<option value = 'lao_peoples_democratic_republic'>Lao Peoples Democratic Republic </option>
<option value = 'latvia'>Latvia </option>
<option value = 'lebanon'>Lebanon </option>
<option value = 'lesotho'>Lesotho </option>
<option value = 'liberia'>Liberia </option>
<option value = 'libyan_arab_jamahiriya'>Libyan Arab Jamahiriya </option>
<option value = 'liechtenstein'>Liechtenstein </option>
<option value = 'lithuania'>Lithuania </option>
<option value = 'luxembourg'>Luxembourg </option>
<option value = 'madagascar'>Madagascar </option>
<option value = 'malawi'>Malawi </option>
<option value = 'malaysia'>Malaysia </option>
<option value = 'maldives'>Maldives </option>
<option value = 'mali'>Mali </option>
<option value = 'malta'>Malta </option>
<option value = 'marshall_islands'>Marshall Islands </option>
<option value = 'mauritania'>Mauritania </option>
<option value = 'mauritius'>Mauritius </option>
<option value = 'mexico_aguascalientes'>Mexico Aguascalientes </option>
<option value = 'mexico_baja_california'>Mexico Baja California </option>
<option value = 'mexico_baja_california_sur'>Mexico Baja California Sur </option>
<option value = 'mexico_campeche'>Mexico Campeche </option>
<option value = 'mexico_chiapas'>Mexico Chiapas </option>
<option value = 'mexico_chihuahua'>Mexico Chihuahua </option>
<option value = 'mexico_coahuila'>Mexico Coahuila </option>
<option value = 'mexico_colima'>Mexico Colima </option>
<option value = 'mexico_durango'>Mexico Durango </option>
<option value = 'mexico_guanajuato'>Mexico Guanajuato </option>
<option value = 'mexico_guerrero'>Mexico Guerrero </option>
<option value = 'mexico_hidalgo'>Mexico Hidalgo </option>
<option value = 'mexico_jalisco'>Mexico Jalisco </option>
<option value = 'mexico_mexican_federal_district'>Mexico Mexican Federal District </option>
<option value = 'mexico_michoacan'>Mexico Michoacan </option>
<option value = 'mexico_morelos'>Mexico Morelos </option>
<option value = 'mexico_nayarit'>Mexico Nayarit </option>
<option value = 'mexico_nuevo_leon'>Mexico Nuevo Leon </option>
<option value = 'mexico_oaxaca'>Mexico Oaxaca </option>
<option value = 'mexico_puebla'>Mexico Puebla </option>
<option value = 'mexico_queretaro'>Mexico Queretaro </option>
<option value = 'mexico_quintana_roo'>Mexico Quintana Roo </option>
<option value = 'mexico_san_luis_potosi'>Mexico San Luis Potosi </option>
<option value = 'mexico_sinaloa'>Mexico Sinaloa </option>
<option value = 'mexico_sonora'>Mexico Sonora </option>
<option value = 'mexico_state_of_mexico'>Mexico State Of Mexico </option>
<option value = 'mexico_tabasco'>Mexico Tabasco </option>
<option value = 'mexico_tamaulipas'>Mexico Tamaulipas </option>
<option value = 'mexico_tlaxcala'>Mexico Tlaxcala </option>
<option value = 'mexico_veracruz'>Mexico Veracruz </option>
<option value = 'mexico_yucatan'>Mexico Yucatan </option>
<option value = 'mexico_zacatecas'>Mexico Zacatecas </option>
<option value = 'micronesia'>Micronesia </option>
<option value = 'monaco'>Monaco </option>
<option value = 'mongolia_west'>Mongolia West </option>
<option value = 'mongolia_east'>Mongolia East </option>
<option value = 'montenegro'>Montenegro </option>
<option value = 'morocco'>Morocco </option>
<option value = 'mozambique'>Mozambique </option>
<option value = 'myanmar'>Myanmar </option>
<option value = 'namibia'>Namibia </option>
<option value = 'nauru'>Nauru </option>
<option value = 'nepal'>Nepal </option>
<option value = 'netherlands'>Netherlands </option>
<option value = 'netherlands_antilles'>Netherlands Antilles </option>
<option value = 'netherlands_aruba'>Netherlands Aruba </option>
<option value = 'new_zealand'>New Zealand </option>
<option value = 'new_zealand_chatham_islands'>New Zealand Chatham Islands </option>
<option value = 'new_zealand_cook_islands'>New Zealand Cook Islands </option>
<option value = 'new_zealand_niue'>New Zealand Niue </option>
<option value = 'new_zealand_tokelau'>New Zealand Tokelau </option>
<option value = 'nicaragua'>Nicaragua </option>
<option value = 'niger'>Niger </option>
<option value = 'nigeria'>Nigeria </option>
<option value = 'norway'>Norway </option>
<option value = 'norway_bouvet_island'>Norway Bouvet Island </option>
<option value = 'norway_jan_mayen'>Norway Jan Mayen </option>
<option value = 'norway_svalbard'>Norway Svalbard </option>
<option value = 'oman'>Oman </option>
<option value = 'pakistan'>Pakistan </option>
<option value = 'palau'>Palau </option>
<option value = 'panama'>Panama </option>
<option value = 'papua_new_guinea'>Papua New Guinea </option>
<option value = 'paraguay'>Paraguay </option>
<option value = 'peru'>Peru </option>
<option value = 'philippines'>Philippines </option>
<option value = 'poland'>Poland </option>
<option value = 'portugal'>Portugal </option>
<option value = 'portugal_azores'>Portugal Azores </option>
<option value = 'qatar'>Qatar </option>
<option value = 'republic_of_korea'>Republic Of Korea </option>
<option value = 'republic_of_moldova'>Republic Of Moldova </option>
<option value = 'romania'>Romania </option>
<option value = 'russia_adygea'>Russia Adygea </option>
<option value = 'russia_agin_buryat'>Russia Agin Buryat </option>
<option value = 'russia_altaskiy_kray'>Russia Altaskiy Kray </option>
<option value = 'russia_altai_republic'>Russia Altai Republic </option>
<option value = 'russia_amur'>Russia Amur </option>
<option value = 'russia_arkhangel'>Russia Arkhangel </option>
<option value = 'russia_astrakhan'>Russia Astrakhan </option>
<option value = 'russia_bashkortostan'>Russia Bashkortostan </option>
<option value = 'russia_belgorod'>Russia Belgorod </option>
<option value = 'russia_bryansk'>Russia Bryansk </option>
<option value = 'russia_buryatia'>Russia Buryatia </option>
<option value = 'russia_chechnya'>Russia Chechnya </option>
<option value = 'russia_chelyabinsk'>Russia Chelyabinsk </option>
<option value = 'russia_chita'>Russia Chita </option>
<option value = 'russia_chukot'>Russia Chukot </option>
<option value = 'russia_chuvashia'>Russia Chuvashia </option>
<option value = 'russia_dagestan'>Russia Dagestan </option>
<option value = 'russia_evenki'>Russia Evenki </option>
<option value = 'russia_ingushetia'>Russia Ingushetia </option>
<option value = 'russia_irkutsk'>Russia Irkutsk </option>
<option value = 'russia_ivanovo'>Russia Ivanovo </option>
<option value = 'russia_jewish_autonomous_oblast'>Russia Jewish Autonomous Oblast </option>
<option value = 'russia_kabardino_balkaria'>Russia Kabardino Balkaria </option>
<option value = 'russia_kaliningrad'>Russia Kaliningrad </option>
<option value = 'russia_kalmykia'>Russia Kalmykia </option>
<option value = 'russia_kaluga'>Russia Kaluga </option>
<option value = 'russia_kamchatka'>Russia Kamchatka </option>
<option value = 'russia_karachay_cherkessia'>Russia Karachay Cherkessia </option>
<option value = 'russia_karelia'>Russia Karelia </option>
<option value = 'russia_kemerovo'>Russia Kemerovo </option>
<option value = 'russia_khabarovsk'>Russia Khabarovsk </option>
<option value = 'russia_khakassia'>Russia Khakassia </option>
<option value = 'russia_khanty_mansi'>Russia Khanty Mansi </option>
<option value = 'russia_kirov'>Russia Kirov </option>
<option value = 'russia_komi'>Russia Komi </option>
<option value = 'russia_koryak'>Russia Koryak </option>
<option value = 'russia_kostroma'>Russia Kostroma </option>
<option value = 'russia_krasnodar'>Russia Krasnodar </option>
<option value = 'russia_krasnoyarsk'>Russia Krasnoyarsk </option>
<option value = 'russia_kurgan'>Russia Kurgan </option>
<option value = 'russia_kursk'>Russia Kursk </option>
<option value = 'russia_leningradskaya_oblast'>Russia Leningradskaya Oblast </option>
<option value = 'russia_lipetsk'>Russia Lipetsk </option>
<option value = 'russia_magadan'>Russia Magadan </option>
<option value = 'russia_mari_el'>Russia Mari El </option>
<option value = 'russia_mordovia'>Russia Mordovia </option>
<option value = 'russia_moscow_city'>Russia Moscow City </option>
<option value = 'russia_moskva'>Russia Moskva </option>
<option value = 'russia_murmansk'>Russia Murmansk </option>
<option value = 'russia_nenets'>Russia Nenets </option>
<option value = 'russia_nizhniy_novgorod'>Russia Nizhniy Novgorod </option>
<option value = 'russia_north_ossetia_alania'>Russia North Ossetia Alania </option>
<option value = 'russia_novgorod'>Russia Novgorod </option>
<option value = 'russia_novosibirsk'>Russia Novosibirsk </option>
<option value = 'russia_omsk'>Russia Omsk </option>
<option value = 'russia_orenburg'>Russia Orenburg </option>
<option value = 'russia_oryol'>Russia Oryol </option>
<option value = 'russia_penza'>Russia Penza </option>
<option value = 'russia_perm_krai'>Russia Perm Krai </option>
<option value = 'russia_primorskiy'>Russia Primorskiy </option>
<option value = 'russia_pskov'>Russia Pskov </option>
<option value = 'russia_rostov'>Russia Rostov </option>
<option value = 'russia_ryazan'>Russia Ryazan </option>
<option value = 'russia_sakha_west'>Russia Sakha West </option>
<option value = 'russia_sakha_central'>Russia Sakha Central </option>
<option value = 'russia_sakha_east'>Russia Sakha East </option>
<option value = 'russia_sakhalin'>Russia Sakhalin </option>
<option value = 'russia_sakhalin_kuril_islands'>Russia Sakhalin Kuril Islands </option>
<option value = 'russia_samara'>Russia Samara </option>
<option value = 'russia_saratov'>Russia Saratov </option>
<option value = 'russia_smolensk'>Russia Smolensk </option>
<option value = 'russia_st_petersburg_city'>Russia St Petersburg City </option>
<option value = 'russia_stavropol'>Russia Stavropol </option>
<option value = 'russia_sverdlovsk'>Russia Sverdlovsk </option>
<option value = 'russia_tambov'>Russia Tambov </option>
<option value = 'russia_tatarstan'>Russia Tatarstan </option>
<option value = 'russia_taymyr'>Russia Taymyr </option>
<option value = 'russia_tomsk'>Russia Tomsk </option>
<option value = 'russia_tula'>Russia Tula </option>
<option value = 'russia_tuva'>Russia Tuva </option>
<option value = 'russia_tver'>Russia Tver </option>
<option value = 'russia_tyumen'>Russia Tyumen </option>
<option value = 'russia_udmurtia'>Russia Udmurtia </option>
<option value = 'russia_ulyanovsk'>Russia Ulyanovsk </option>
<option value = 'russia_ust_ordyn_buryat'>Russia Ust Ordyn Buryat </option>
<option value = 'russia_vladimir'>Russia Vladimir </option>
<option value = 'russia_volgograd'>Russia Volgograd </option>
<option value = 'russia_vologda'>Russia Vologda </option>
<option value = 'russia_voronezh'>Russia Voronezh </option>
<option value = 'russia_yamalo_nenets'>Russia Yamalo Nenets </option>
<option value = 'russia_yaroslavl'>Russia Yaroslavl </option>
<option value = 'rwanda'>Rwanda </option>
<option value = 'saint_kitts_and_nevis'>Saint Kitts And Nevis </option>
<option value = 'saint_lucia'>Saint Lucia </option>
<option value = 'saint_vincent_and_the_grenadines'>Saint Vincent And The Grenadines </option>
<option value = 'samoa'>Samoa </option>
<option value = 'san_marino'>San Marino </option>
<option value = 'sao_tome_and_principe'>Sao Tome And Principe </option>
<option value = 'saudi_arabia'>Saudi Arabia </option>
<option value = 'senegal'>Senegal </option>
<option value = 'serbia'>Serbia </option>
<option value = 'seychelles'>Seychelles </option>
<option value = 'sierra_leone'>Sierra Leone </option>
<option value = 'singapore'>Singapore </option>
<option value = 'slovakia'>Slovakia </option>
<option value = 'slovenia'>Slovenia </option>
<option value = 'solomon_islands'>Solomon Islands </option>
<option value = 'somalia'>Somalia </option>
<option value = 'south_africa'>South Africa </option>
<option value = 'spain'>Spain </option>
<option value = 'spain_canary_islands'>Spain Canary Islands </option>
<option value = 'sri_lanka'>Sri Lanka </option>
<option value = 'sudan'>Sudan </option>
<option value = 'suriname'>Suriname </option>
<option value = 'swaziland'>Swaziland </option>
<option value = 'sweden'>Sweden </option>
<option value = 'switzerland'>Switzerland </option>
<option value = 'syria'>Syria </option>
<option value = 'syrian_arab_republic'>Syrian Arab Republic </option>
<option value = 'tajikistan'>Tajikistan </option>
<option value = 'thailand'>Thailand </option>
<option value = 'fyro_macedonia'>Fyro Macedonia </option>
<option value = 'timor_leste'>Timor Leste </option>
<option value = 'togo'>Togo </option>
<option value = 'tonga'>Tonga </option>
<option value = 'trinidad_and_tobago'>Trinidad And Tobago </option>
<option value = 'tunisia'>Tunisia </option>
<option value = 'turkey'>Turkey </option>
<option value = 'turkmenistan'>Turkmenistan </option>
<option value = 'tuvalu'>Tuvalu </option>
<option value = 'uganda'>Uganda </option>
<option value = 'ukraine'>Ukraine </option>
<option value = 'united_arab_emirates'>United Arab Emirates </option>
<option value = 'uk'>Uk </option>
<option value = 'uk_akrotiri'>Uk Akrotiri </option>
<option value = 'uk_anguilla'>Uk Anguilla </option>
<option value = 'uk_bermuda'>Uk Bermuda </option>
<option value = 'uk_british_indian_ocean_territory'>Uk British Indian Ocean Territory </option>
<option value = 'uk_british_virgin_islands'>Uk British Virgin Islands </option>
<option value = 'uk_cayman_islands'>Uk Cayman Islands </option>
<option value = 'uk_dhekelia'>Uk Dhekelia </option>
<option value = 'uk_falkland_islands'>Uk Falkland Islands </option>
<option value = 'uk_gibraltar'>Uk Gibraltar </option>
<option value = 'uk_guernsey'>Uk Guernsey </option>
<option value = 'uk_isle_of_man'>Uk Isle Of Man </option>
<option value = 'uk_jersey'>Uk Jersey </option>
<option value = 'uk_montserrat'>Uk Montserrat </option>
<option value = 'uk_pitcairn_islands'>Uk Pitcairn Islands </option>
<option value = 'uk_saint_helena_ascensiont_tristan_da_cuhna'>Uk Saint Helena Ascensiont Tristan Da Cuhna </option>
<option value = 'uk_south_georgia_and_the_south_sandwich_islands'>Uk South Georgia And The South Sandwich Islands </option>
<option value = 'uk_turks_and_caicos_islands'>Uk Turks And Caicos Islands </option>
<option value = 'united_republic_of_tanzania'>United Republic Of Tanzania </option>
<option value = 'usa_alabama'>Usa Alabama </option>
<option value = 'usa_alabama_phenix_city_unofficial'>Usa Alabama Phenix City Unofficial </option>
<option value = 'usa_alaska'>Usa Alaska </option>
<option value = 'usa_aleutian_islands'>Usa Aleutian Islands </option>
<option value = 'usa_arizona'>Usa Arizona </option>
<option value = 'usa_arizona_navajo_nation'>Usa Arizona Navajo Nation </option>
<option value = 'usa_arizona_navajo_nation_hopi_reservation'>Usa Arizona Navajo Nation Hopi Reservation </option>
<option value = 'usa_arkansas'>Usa Arkansas </option>
<option value = 'usa_california'>Usa California </option>
<option value = 'usa_colorado'>Usa Colorado </option>
<option value = 'usa_connecticut'>Usa Connecticut </option>
<option value = 'usa_delaware'>Usa Delaware </option>
<option value = 'usa_district_of_columbia'>Usa District Of Columbia </option>
<option value = 'usa_florida'>Usa Florida </option>
<option value = 'usa_florida_west'>Usa Florida West </option>
<option value = 'usa_georgia'>Usa Georgia </option>
<option value = 'usa_hawaii'>Usa Hawaii </option>
<option value = 'usa_idaho_south'>Usa Idaho South </option>
<option value = 'usa_idaho_north'>Usa Idaho North </option>
<option value = 'usa_illinois'>Usa Illinois </option>
<option value = 'usa_indiana'>Usa Indiana </option>
<option value = 'usa_indiana_counties'>Usa Indiana Counties </option>
<option value = 'usa_iowa'>Usa Iowa </option>
<option value = 'usa_kansas'>Usa Kansas </option>
<option value = 'usa_kansas_counties'>Usa Kansas Counties </option>
<option value = 'usa_kentucky_west'>Usa Kentucky West </option>
<option value = 'usa_kentucky_east'>Usa Kentucky East </option>
<option value = 'usa_louisiana'>Usa Louisiana </option>
<option value = 'usa_maine'>Usa Maine </option>
<option value = 'usa_maryland'>Usa Maryland </option>
<option value = 'usa_massachusetts'>Usa Massachusetts </option>
<option value = 'usa_michigan'>Usa Michigan </option>
<option value = 'usa_michigan_counties'>Usa Michigan Counties </option>
<option value = 'usa_minnesota'>Usa Minnesota </option>
<option value = 'usa_mississippi'>Usa Mississippi </option>
<option value = 'usa_missouri'>Usa Missouri </option>
<option value = 'usa_montana'>Usa Montana </option>
<option value = 'usa_nebraska_west'>Usa Nebraska West </option>
<option value = 'usa_nebraska_east_central'>Usa Nebraska East Central </option>
<option value = 'usa_nevada'>Usa Nevada </option>
<option value = 'usa_nevada_others'>Usa Nevada Others </option>
<option value = 'usa_new_hampshire'>Usa New Hampshire </option>
<option value = 'usa_new_jersey'>Usa New Jersey </option>
<option value = 'usa_new_mexico'>Usa New Mexico </option>
<option value = 'usa_new_york'>Usa New York </option>
<option value = 'usa_north_carolina'>Usa North Carolina </option>
<option value = 'usa_north_dakota'>Usa North Dakota </option>
<option value = 'usa_north_dakota_south_west'>Usa North Dakota South West </option>
<option value = 'usa_ohio'>Usa Ohio </option>
<option value = 'usa_oklahoma'>Usa Oklahoma </option>
<option value = 'usa_oklahoma_kenton'>Usa Oklahoma Kenton </option>
<option value = 'usa_oregon'>Usa Oregon </option>
<option value = 'usa_oregon_northern_malheur_county'>Usa Oregon Northern Malheur County </option>
<option value = 'usa_pennsylvania'>Usa Pennsylvania </option>
<option value = 'usa_rhode_island'>Usa Rhode Island </option>
<option value = 'usa_south_carolina'>Usa South Carolina </option>
<option value = 'usa_south_dakota_west'>Usa South Dakota West </option>
<option value = 'usa_south_dakota_east'>Usa South Dakota East </option>
<option value = 'usa_tennessee'>Usa Tennessee </option>
<option value = 'usa_tennessee_east'>Usa Tennessee East </option>
<option value = 'usa_texas'>Usa Texas </option>
<option value = 'usa_texas_counties'>Usa Texas Counties </option>
<option value = 'usa_utah'>Usa Utah </option>
<option value = 'usa_vermont'>Usa Vermont </option>
<option value = 'usa_virginia'>Usa Virginia </option>
<option value = 'usa_washington'>Usa Washington </option>
<option value = 'usa_west_virginia'>Usa West Virginia </option>
<option value = 'usa_wisconsin'>Usa Wisconsin </option>
<option value = 'usa_wyoming'>Usa Wyoming </option>
<option value = 'usa_american_samoa'>Usa American Samoa </option>
<option value = 'usa_american_guam'>Usa American Guam </option>
<option value = 'usa_navassa_island'>Usa Navassa Island </option>
<option value = 'usa_northern_mariana_islands'>Usa Northern Mariana Islands </option>
<option value = 'usa_puerto_rico'>Usa Puerto Rico </option>
<option value = 'usa_pir_baker_island'>Usa Pir Baker Island </option>
<option value = 'usa_pir_howland_island'>Usa Pir Howland Island </option>
<option value = 'usa_pir_jarvis_island'>Usa Pir Jarvis Island </option>
<option value = 'usa_pir_johnston_atoll'>Usa Pir Johnston Atoll </option>
<option value = 'usa_pir_kingman_reef'>Usa Pir Kingman Reef </option>
<option value = 'usa_pir_midway_islands'>Usa Pir Midway Islands </option>
<option value = 'usa_pir_palmyra_atoll'>Usa Pir Palmyra Atoll </option>
<option value = 'usa_virgin_islands'>Usa Virgin Islands </option>
<option value = 'usa_wake_island'>Usa Wake Island </option>
<option value = 'uruguay'>Uruguay </option>
<option value = 'uzbekistan'>Uzbekistan </option>
<option value = 'vanuatu'>Vanuatu </option>
<option value = 'viet_nam'>Viet Nam </option>
<option value = 'western_sahara'>Western Sahara </option>
<option value = 'yemen'>Yemen </option>
<option value = 'zambia'>Zambia </option>
<option value = 'zimbabwe'>Zimbabwe </option>
</select>
</div>
<div id="mybody"></div>
<script type="text/javascript">
	var req1,req2,df,jt;
	var ServerDSTCheck = new Date(parseFloat(<?php echo $time_this_server_javascript ?>)).getTime();

	creator("container_1","div","id","mybody");
	creator("country_label_1","div","id","container_1");
	creator("offset_label_1","div","id","container_1");
	creator("offset_1","div","id","container_1");
	creator("ap_offset_value_1","span","id","offset_1");
	creator("ap_nice_offset_1","span","id","offset_1");
	creator("button_24_1","span","id","offset_1");
	
	creator("container_2","div","id","mybody");
	creator("country_label_2","div","id","container_2");
	creator("offset_label_2","div","id","container_2");
	creator("offset_2","div","id","container_2");
	creator("ap_offset_value_2","span","id","offset_2");
	creator("ap_nice_offset_2","span","id","offset_2");
	creator("button_24_2","span","id","offset_2");

	function wrapper(l,inst)
	{
		this.chgChk = new Date().getTime();
		this.index = inst;
		wrapper.instances[this.index] = this;
		this.req_loc = 'clock_data.php?j='+l;
		this.resp;
		this.df;
		this.jt;
		this.result;
		this.container = "container_" + inst;
		this.o_label = "offset_label_" + inst;
		this.o_div = "offset_" + inst;
		this.ap_val = "ap_offset_value_" + inst;
		this.ap_no = "ap_nice_offset_" + inst;
		this.button = "button_24_" + inst;
		this.clockInstance;
		this.instance = inst;
		this.button_int = "<button name='24_sw_"+inst+"' id='24_sw_"+inst+"' onclick='wrapper.instances["+inst+"].clockInstance.switch_time()'>Switch to 24 hour display</button>";
		this.o_label = "offset_label_" + inst;
		if (this.resp == null || this.result == null)
		{
			this.resp = new ajax_request(this.req_loc);
			this.result = new ajax_request('x.php');
		}
		else
		{
			if (this.resp.xmlHttp.responseText != null)
			{
				this.check_dst();
			}
		}
		
		setInterval('wrapper.instances['+inst+'].check_dst()',500);
	}
	wrapper.instances = []
	wrapper.prototype.check_dst = function ()
	{
		eval(this.resp.xmlHttp.responseText);
		this.jt = jt;
		this.df = df;
		this.chgChkInt = new Date().getTime();
		if ((this.chgChkInt < this.chgChk) || ((this.chgChkInt-this.chgChk) > 1000) || (this.chgChkInt == this.chgChk) || this.result == null)
		{
			this.result = new ajax_request('x.php');
			this.clockInstance = null;
		}
		if (this.result != null && this.clockInstance == null)
		{
			if (parseFloat(this.result.xmlHttp.responseText) > 1)
			{
				this.srv_mls = parseFloat(this.result.xmlHttp.responseText);
				this.clockInstance = new calc(this.srv_mls,this.df,this.jt,this.instance);
				writer(this.button_int,this.button,this.o_div);
			}
		}
		if (this.clockInstance != null)
		{
			ServerDSTCheck+=(this.chgChkInt-this.chgChk);
			this.clockInstance.to_utc();
			this.clockInstance.nice_offset();
			this.clockInstance.offset_time();
			writer(this.jt,this.o_label,this.container);
			writer(this.clockInstance.apOffsetTime,this.ap_val,this.o_div);
			writer(this.clockInstance.niceOffset,this.ap_no,this.o_div);
		}
		this.chgChk = new Date().getTime();
	}	
</script>
</body>
</html>
	
